export const ExpensesArray = [
  {
    id: Math.random().toLocaleString(),
    title: "Groceries",
    description: "Weekly grocery shopping",
    amount: 150.25,
    date: "2024-07-15",
  },
  {
    id: Math.random().toLocaleString(),
    title: "Rent",
    description: "Monthly house rent",
    amount: 1200.0,
    date: "2024-07-01",
  },
  {
    id: Math.random().toLocaleString(),
    title: "Utilities",
    description: "Electricity and water bills",
    amount: 85.75,
    date: "2024-07-05",
  },
  {
    id: Math.random().toLocaleString(),
    title: "Internet",
    description: "Monthly internet subscription",
    amount: 50.0,
    date: "2024-07-08",
  },
  {
    id: Math.random().toLocaleString(),
    title: "Transportation",
    description: "Monthly metro pass",
    amount: 75.0,
    date: "2024-07-10",
  },
  {
    id: Math.random().toLocaleString(),
    title: "Dining",
    description: "Dinner at a restaurant",
    amount: 60.5,
    date: "2024-07-12",
  },
  {
    id: Math.random().toLocaleString(),
    title: "Gym",
    description: "Monthly gym membership",
    amount: 40.0,
    date: "2024-07-03",
  },
  {
    id: Math.random().toLocaleString(),
    title: "Insurance",
    description: "Health insurance premium",
    amount: 200.0,
    date: "2024-07-20",
  },
  {
    id: Math.random().toLocaleString(),
    title: "Entertainment",
    description: "Movie tickets",
    amount: 30.0,
    date: "2024-07-18",
  },
  {
    id: Math.random().toLocaleString(),
    title: "Books",
    description: "Purchase of new books",
    amount: 45.0,
    date: "2024-07-22",
  },
];
